# Generated by Django 3.0.7 on 2020-06-28 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niicodeCo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='post',
            name='modified_date',
        ),
    ]
